import argparse

def parse_args():
    parser = argparse.ArgumentParser("few_shot_learing")
    parser.add_argument("--epochs", default=50, help="训练轮次")
    parser.add_argument("--in_channel", default=5, help="测井曲线条数")
    parser.add_argument("--classes", default=10, help="分类数")
    parser.add_argument("--learning_rate", default=0.0005, help="学习率")
    parser.add_argument("--decay", default=0.98, help="学习率衰减")
    parser.add_argument("--gpu_id", default="3",  help="gpu的id")
    parser.add_argument("--seed", default=42, help="随机数种子")
    parser.add_argument("--log_dir_path", default="few_shot_228/cpc", help="日志文件存储位置")
    parser.add_argument("--print_period", default=10, help="打印间隔")
    parser.add_argument("--pretrained", default=False, help="是否加载预训练模型")
    parser.add_argument("--pretrained_filepath", default="", help="预训练模型位置")
    parser.add_argument("--dir", default="../data/well_data/", help="数据集位置")
    # parser.add_argument("--train_dir", default="../data/augment_data/train_data/", help="训练集位置")
    # parser.add_argument("--val_dir", default="../data/augment_data/val_data/", help="验证集位置")
    parser.add_argument("--train_dir", default="../data/well_228_old/train/", help="训练集位置")
    parser.add_argument("--val_dir", default="../data/well_228_old/test/", help="验证集位置")
    parser.add_argument("--slice_length", default=96, help="切片长")
    parser.add_argument("--slice_step", default=96, help="滑动步长")
    parser.add_argument("--train_well_num", default=10, help="进行训练的井数")
    parser.add_argument("--val_well_num", default=20, help="进行训练的井数")
    parser.add_argument("--frequency_aug", default="None", help="是否进行频域增广，以及进行什么频域增广，wave_1, wave_2, False")
    parser.add_argument("--depth_aug", default="False", help="是否进行时域增广，以及进行什么增广")
    parser.add_argument("--classification_name", default="地质分层", help="测井解释任务类型，地质分层、油气水划分、储层划分")
    parser.add_argument("--batchsize", default=512)
    parser.add_argument("--layers", type=int, default=4, help='搜索时模型堆叠层数')
    parser.add_argument('--arch', type=str, default='DARTS_10', help='which architecture to use') #要使用的网络架构，默认为'DARTS'。指定了使用的神经网络架构。
    parser.add_argument("--is_nas", default=True, help="是否采用NAS搜索得到的模型作为Encoder")
    parser.add_argument("--temperature", default=0.1, help="计算InfoLoss时的温度系数")
    parser.add_argument("--patience", default=10, help="当多轮loss不在降低时，停止cpc的训练")

    args = parser.parse_args()
    return args

def classifier_parse_args():
    parser = argparse.ArgumentParser("few_shot_learing")
    parser.add_argument("--epochs", default=100, help="训练轮次")
    parser.add_argument("--in_channel", default=5, help="测井曲线条数")
    parser.add_argument("--classes", default=10, help="分类数")
    parser.add_argument("--learning_rate", default=0.0005, help="学习率")
    parser.add_argument("--decay", default=0.98, help="学习率衰减")
    parser.add_argument("--gpu_id", default="3",  help="gpu的id")
    parser.add_argument("--seed", default=42, help="随机数种子")
    parser.add_argument("--log_dir_path", default="few_shot_228/classifier", help="日志文件存储位置")
    parser.add_argument("--print_period", default=10, help="打印间隔")
    parser.add_argument("--pretrained", default=True, help="是否加载预训练模型")
    parser.add_argument("--pretrained_filepath", default="log/cpc/few_shot_228/cpc/地质分层_cpc_06_27_2024_18_55_18/best_epoch_model.pth", help="预训练模型位置")
    parser.add_argument("--dir", default="../data/well_data/", help="数据集位置")
    # parser.add_argument("--train_dir", default="../data/augment_data/train_data/", help="训练集位置")
    # parser.add_argument("--val_dir", default="../data/augment_data/val_data/", help="验证集位置")
    parser.add_argument("--train_dir", default="../data/well_228_old/train/", help="训练集位置")
    parser.add_argument("--val_dir", default="../data/well_228_old/test/", help="验证集位置")
    parser.add_argument("--slice_length", default=96, help="切片长")
    parser.add_argument("--slice_step", default=96, help="滑动步长")
    parser.add_argument("--train_well_num", default=10, help="进行训练的井数")
    parser.add_argument("--val_well_num", default=20, help="进行训练的井数")
    parser.add_argument("--frequency_aug", default="None", help="是否进行频域增广，以及进行什么频域增广，wave_1, wave_2, False")
    parser.add_argument("--depth_aug", default="False", help="是否进行时域增广，以及进行什么增广")
    parser.add_argument("--classification_name", default="地质分层", help="测井解释任务类型，地质分层、油气水划分、储层划分")
    parser.add_argument("--batchsize", default=1024)
    parser.add_argument("--layers", type=int, default=4, help='搜索时模型堆叠层数')
    parser.add_argument('--arch', type=str, default='DARTS_10', help='which architecture to use') #要使用的网络架构，默认为'DARTS'。指定了使用的神经网络架构。
    parser.add_argument("--is_nas", default=True, help="是否采用NAS搜索得到的模型作为Encoder")
    parser.add_argument("--drop_path_prob", type=float, default=0, help='drop path probability')
    parser.add_argument("--temperature", default=0.1, help="计算InfoLoss时的温度系数")

    args = parser.parse_args()
    return args